

package com.icyrockton.xjson.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.icyrockton.xjson.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/test-data/codegen")
@TestDataPath("$PROJECT_ROOT")
public class CodeGenTestRunnerGenerated extends AbstractCodeGenTestRunner {
    @Test
    public void testAllFilesPresentInCodegen() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test-data/codegen"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("complexDataClass.kt")
    public void testComplexDataClass() throws Exception {
        runTest("src/test-data/codegen/complexDataClass.kt");
    }

    @Test
    @TestMetadata("simpleDataClass.kt")
    public void testSimpleDataClass() throws Exception {
        runTest("src/test-data/codegen/simpleDataClass.kt");
    }
}
