

package com.icyrockton.xjson.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.icyrockton.xjson.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/test-data/fir")
@TestDataPath("$PROJECT_ROOT")
public class FirTestRunnerGenerated extends AbstractFirTestRunner {
    @Test
    public void testAllFilesPresentInFir() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/test-data/fir"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("simpleDataClass.kt")
    public void testSimpleDataClass() throws Exception {
        runTest("src/test-data/fir/simpleDataClass.kt");
    }
}
